GET http://localhost:5000

### Users
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "Adi Munawar",
    "email": "the.panzer31@gmail.com",
    "password": "munawar31"
}